name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Запуск unit-тестов
        run: |
          pytest  # Запустите ваши тесты

      - name: Проверка безопасности кода
        run: |
          pip install bandit
          bandit -r .  # Запустите проверку безопасности

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Генерация changelog
        run: |
          bash generate_changelog.sh   # Убедитесь, что скрипт имеет права на выполнение

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Публикация на GitHub Pages
        run: |
          git add changelog.md
          git commit -m "Обновление changelog"
